-- Copyright (c) 2026 Shane Smith / Sassy Consulting LLC. All rights reserved.
-- Proprietary source. This notice is Copyright Management Information (17 U.S.C. 1202); removal or alteration prohibited.
-- CodeMark: SCLLC1-sassyconsultingllc_cloudflare-7DULGOKSVVOD
-- ============================================================================
-- Sassy Consulting LLC - Stripe -> Lemon Squeezy column rename
-- Copyright (c) 2026 Sassy Consulting LLC
--
-- STATUS: APPLIED to the remote `contact-submissions` D1 database
--         (verified 2026-05-28: licenses.payment_ref and products.ls_variant_id
--         already exist; stripe_session_id / stripe_price_id no longer present).
--
-- This file is kept as a historical record of the rename. It is intentionally
-- a no-op now because SQLite does NOT support `ALTER TABLE ... RENAME COLUMN
-- IF EXISTS`, and re-running the ALTERs against an already-migrated database
-- errors with `no such column: "stripe_session_id"`. Leaving the statements
-- live would break any "apply every migration" workflow.
--
-- Original intent (do not re-run):
--   ALTER TABLE licenses RENAME COLUMN stripe_session_id TO payment_ref;
--   ALTER TABLE products RENAME COLUMN stripe_price_id   TO ls_variant_id;
--
-- If you spin up a fresh D1 instance, uncomment the two ALTERs above and run
-- this file once. Otherwise leave it alone.
-- ============================================================================

SELECT 'migration 0004 already applied — no-op' AS status;
